export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-16 sm:px-6">
      <div className="mb-8 rounded-lg border border-zinc-800 bg-zinc-900/50 p-4 text-sm text-zinc-400">
        This is a beta-stage terms of service and may change as the product
        evolves. By using HoopSpark you agree to the terms below.
      </div>

      <h1 className="mb-8 text-4xl font-bold">Terms of Service</h1>
      <p className="mb-8 text-sm text-zinc-500">Last updated: April 25, 2026</p>

      <div className="space-y-2 text-zinc-300">
        <h2 className="mt-8 mb-3 text-xl font-semibold text-white">
          Who Can Use HoopSpark
        </h2>
        <p className="leading-relaxed">
          You must be at least 13 years old to use HoopSpark. If you are under
          18, you must have the consent of a parent or legal guardian. By
          creating an account, you confirm that you meet these requirements.
        </p>

        <h2 className="mt-8 mb-3 text-xl font-semibold text-white">
          What the Service Is
        </h2>
        <p className="leading-relaxed">
          HoopSpark is an AI-powered basketball film analysis tool currently in
          beta. You upload video clips and receive automated feedback on your
          play. The service is provided as-is during this beta period. Feedback
          is generated by AI and is not a substitute for professional coaching.
          We make no warranties, express or implied, about the accuracy or
          completeness of feedback.
        </p>

        <h2 className="mt-8 mb-3 text-xl font-semibold text-white">
          Your Responsibilities
        </h2>
        <p className="leading-relaxed">
          You are responsible for the content you upload. You may only upload
          video files that you own or have explicit rights to share. You may not
          upload content that is illegal, defamatory, obscene, or that infringes
          on the intellectual property rights of others. You agree not to
          misuse the service, attempt to reverse-engineer the AI system, or
          interfere with the platform&apos;s operation.
        </p>

        <h2 className="mt-8 mb-3 text-xl font-semibold text-white">
          Intellectual Property
        </h2>
        <p className="leading-relaxed">
          You retain ownership of the video content you upload. By uploading,
          you grant HoopSpark a limited license to process your videos solely
          for the purpose of generating feedback for you. We do not claim
          ownership of your content. The HoopSpark platform, AI models, and
          branding remain the intellectual property of HoopSpark.
        </p>

        <h2 className="mt-8 mb-3 text-xl font-semibold text-white">
          Account Termination
        </h2>
        <p className="leading-relaxed">
          We reserve the right to suspend or terminate accounts that violate
          these terms, engage in abusive behavior, or misuse the service — with
          or without prior notice. You may delete your account at any time by
          contacting us at{" "}
          <a
            href="mailto:hello@hoopspark.ai"
            className="text-[#FF6B2C] hover:underline"
          >
            hello@hoopspark.ai
          </a>
          .
        </p>

        <h2 className="mt-8 mb-3 text-xl font-semibold text-white">
          Beta Disclaimer
        </h2>
        <p className="leading-relaxed">
          HoopSpark is currently in beta. This means the service may have bugs,
          downtime, or features that change without notice. We provide the
          service as-is and disclaim all warranties to the fullest extent
          permitted by law. We are not liable for any loss of data, missed
          opportunities, or decisions made based on AI-generated feedback.
        </p>

        <h2 className="mt-8 mb-3 text-xl font-semibold text-white">
          Changes to These Terms
        </h2>
        <p className="leading-relaxed">
          We may update these terms as the product evolves. Continued use of
          the service after changes are posted constitutes acceptance of the
          revised terms.
        </p>

        <h2 className="mt-8 mb-3 text-xl font-semibold text-white">
          Contact
        </h2>
        <p className="leading-relaxed">
          Questions? Email{" "}
          <a
            href="mailto:hello@hoopspark.ai"
            className="text-[#FF6B2C] hover:underline"
          >
            hello@hoopspark.ai
          </a>
          .
        </p>
      </div>
    </div>
  );
}
